version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/container/app/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/container/" # Location of package manifests
    schedule:
      interval: "daily"
