version: "3.9"

services:
  flask:
    build: container
    environment:
      - REQUIREMENTS=requirements.txt
    volumes:
      - ./container/app:/app
    ports:
      - "8000:8000"
    command: gunicorn -w 4 