version: "3.9"

services:
  socialmediacert:
    build: container
    ports:
      - "8000:8000"
    volumes:
      - ./container/app:/app
    environment:
      - FLASK_DEBUG=True
    command: gunicorn --reload -w 1 'socialmediacert:create_app()'
